all:
   children:
        thing1:
            vars:
               foo: bar
               stuff: yuck
            hosts:
               abc.thing.com:
               abc2.thing.com:
        thing2:
            vars:
               hello: goodbye
            hosts:
               cdf.thing.com:
        things:
            vars:
               group: stuff
               pkg_MULECORE: 
                  group: com.mulesoft
                  module: mule-ee-distribution-standalone
                  ext: tgz
                  version: 4.3.0
            children:
               thing1:
               thing2:
