all:
   children:
        thing1:
            vars:
               foo: bar
               stuff: yuck
               pkg_MULECORE:
                  version: 4.4.4
            hosts:
               devbox:
        thing2:
            vars:
               hello: goodbye
               pkg_MULECORE:
                  version: 5.0.0
            hosts:
               cdf.thing.com:
        things:
            vars:
               group: stuff
               pkg_MULECORE: 
                  group: com.mulesoft
                  module: mule-ee-distribution-standalone
                  ext: tgz
                  version: 4.3.0
            children:
               thing1:
               thing2:
