- name: Install Docker
  hosts: all
  tasks:
        
    - name: Add Docker yum repo
      yum_repository:
        name: docker-ce
        description: Docker CE Stable
        baseurl: https://download.docker.com/linux/centos/7/x86_64/stable
        gpgcheck: yes
        gpgkey: https://download.docker.com/linux/centos/gpg

   - name: Add Centos Extras yum repo
     yum_repository:
        name: centos-extras
        description: Centos Extras
        baseurl: http://mirror.centos.org/centos/7/extras/x86_64
        gpgcheck: no

   - name: Install Docker
     package:
        name: 
          - yum-utils 
          - device-mapper-persistent-data
          - lvm2
          - docker-ce
        state: present 
