- name: Install Docker
  hosts: all
  tasks:
    - name: Install packages
      package:
         name: 
           - yum-utils 
           - device-mapper-persistent-data 
           - lvm2
         state: present
         
    - name: Add Docker-CE repo
      yum_repository:
         name: docker-ce
         
