- name: Install Docker
  hosts: all
  tasks:
        
    - name: debug
      debug:
         msg: "{{ pkg_MULECORE.version }}"
        
        
    - name: debug
      debug:
         msg: "{{ pkg_MULECORE.group }} {{ pkg_MULECORE.module }} {{ pkg_MULECORE.version }}"
